export const LANGS={ko:{name:'한국어',speech:'ko-KR'},ja:{name:'일본어',speech:'ja-JP'},en:{name:'English',speech:'en-US'}};

export const LESSONS=[
{id:'l01',level:1,title:'첫 인사',topic:'인사',ko:'안녕하세요. 만나서 반가워요.',ja:'こんにちは。お会いできてうれしいです。',jaKana:'こんにちは。おあいできて うれしいです。',en:'Hello. Nice to meet you.',literal:'안녕하세요. 만나게 되어 기쁩니다.',words:[['안녕하세요','こんにちは','hello'],['만나다','会う','meet'],['반갑다','うれしい','glad']],grammar:'일본어의 〜できて는 “~할 수 있어서/하게 되어”의 느낌을 만들고, 영어 Nice to meet you는 첫 만남의 고정 표현입니다.',reading:'今日は新しいクラスの初日です。ミナさんは隣の人にあいさつしました。',readingKo:'오늘은 새 수업 첫날입니다. 미나 씨는 옆 사람에게 인사했습니다.',question:'미나 씨는 무엇을 했나요?',answer:'옆 사람에게 인사했습니다.'},
{id:'l02',level:1,title:'감사 표현',topic:'인사',ko:'도와주셔서 정말 감사합니다.',ja:'手伝ってくれて、本当にありがとうございます。',jaKana:'てつだってくれて、ほんとうに ありがとうございます。',en:'Thank you so much for helping me.',literal:'나를 도와준 것에 대해 매우 감사합니다.',words:[['돕다','手伝う','help'],['정말','本当に','really'],['감사하다','感謝する','thank']],grammar:'일본어 〜てくれて는 상대가 나를 위해 해 준 행동에 감사를 나타냅니다. 영어 for + 동명사는 감사의 이유를 설명합니다.',reading:'駅で道が分からなかった時、大学生が地図を見せてくれました。',readingKo:'역에서 길을 몰랐을 때 대학생이 지도를 보여 주었습니다.',question:'누가 지도를 보여 주었나요?',answer:'대학생이 보여 주었습니다.'},
{id:'l03',level:1,title:'오늘 계획',topic:'일상',ko:'오늘은 무엇을 할 거예요?',ja:'今日は何をする予定ですか。',jaKana:'きょうは なにを する よていですか。',en:'What are you going to do today?',literal:'오늘 무엇을 할 예정입니까?',words:[['오늘','今日','today'],['무엇','何','what'],['예정','予定','plan']],grammar:'일본어 予定です는 계획을, 영어 be going to는 이미 정한 미래 행동을 나타냅니다.',reading:'ユジンさんは午前中に勉強して、午後は友達と映画を見ます。',readingKo:'유진 씨는 오전에 공부하고 오후에는 친구와 영화를 봅니다.',question:'유진 씨는 오후에 무엇을 하나요?',answer:'친구와 영화를 봅니다.'},
{id:'l04',level:1,title:'주문하기',topic:'식당',ko:'이것 하나 주세요.',ja:'これを一つください。',jaKana:'これを ひとつ ください。',en:'One of these, please.',literal:'이것을 하나 주세요.',words:[['이것','これ','this'],['하나','一つ','one'],['주세요','ください','please give']],grammar:'일본어 〜をください는 물건 주문의 기본형입니다. 영어는 명사구 뒤에 please를 붙이면 자연스럽습니다.',reading:'パン屋で新しいパンを見つけました。店員に指をさして注文しました。',readingKo:'빵집에서 새로운 빵을 발견했습니다. 점원에게 손가락으로 가리켜 주문했습니다.',question:'어디에서 주문했나요?',answer:'빵집에서 주문했습니다.'},
{id:'l05',level:2,title:'길 묻기',topic:'여행',ko:'역까지 어떻게 가면 돼요?',ja:'駅までどうやって行けばいいですか。',jaKana:'えきまで どうやって いけば いいですか。',en:'How can I get to the station?',literal:'역까지 어떻게 가면 좋습니까?',words:[['역','駅','station'],['어떻게','どうやって','how'],['가다','行く','go']],grammar:'일본어 〜ばいいですか는 방법이나 조언을 물을 때 씁니다. 영어 get to는 목적지에 도착하다라는 뜻입니다.',reading:'駅はこの道をまっすぐ進んで、二つ目の信号を右に曲がった所です。',readingKo:'역은 이 길을 곧장 가서 두 번째 신호에서 오른쪽으로 돌면 있는 곳입니다.',question:'몇 번째 신호에서 돌아야 하나요?',answer:'두 번째 신호에서 돌아야 합니다.'},
{id:'l06',level:2,title:'시간 약속',topic:'약속',ko:'내일 세 시에 만나는 건 어때요?',ja:'明日の三時に会うのはどうですか。',jaKana:'あしたの さんじに あうのは どうですか。',en:'How about meeting at three tomorrow?',literal:'내일 세 시에 만나는 것은 어떻습니까?',words:[['내일','明日','tomorrow'],['세 시','三時','three o’clock'],['어때요','どうですか','how about']],grammar:'일본어 동사 사전형 + のはどうですか, 영어 How about + 동명사는 제안을 만듭니다.',reading:'二人は土曜日にカフェで会うことにしました。',readingKo:'두 사람은 토요일에 카페에서 만나기로 했습니다.',question:'두 사람은 어디에서 만나나요?',answer:'카페에서 만납니다.'},
{id:'l07',level:2,title:'취향 말하기',topic:'취미',ko:'저는 조용한 음악을 듣는 것을 좋아해요.',ja:'私は静かな音楽を聴くのが好きです。',jaKana:'わたしは しずかな おんがくを きくのが すきです。',en:'I like listening to quiet music.',literal:'나는 조용한 음악을 듣는 것이 좋습니다.',words:[['조용하다','静か','quiet'],['음악','音楽','music'],['듣다','聴く','listen']],grammar:'일본어 동사 + のが好き, 영어 like + 동명사로 취향을 표현합니다.',reading:'仕事が終わった後、部屋で音楽を聴くと気持ちが落ち着きます。',readingKo:'일이 끝난 뒤 방에서 음악을 들으면 마음이 차분해집니다.',question:'언제 음악을 듣나요?',answer:'일이 끝난 뒤에 듣습니다.'},
{id:'l08',level:2,title:'경험 묻기',topic:'경험',ko:'일본에 가 본 적이 있어요?',ja:'日本へ行ったことがありますか。',jaKana:'にほんへ いったことが ありますか。',en:'Have you ever been to Japan?',literal:'일본에 간 경험이 있습니까?',words:[['일본','日本','Japan'],['가 본 적','行ったこと','experience of going'],['있다','ある','have']],grammar:'일본어 과거형 + ことがある, 영어 Have you ever + 과거분사는 경험을 묻습니다.',reading:'私は去年初めて大阪へ行きました。食べ物がおいしくて、また行きたいです。',readingKo:'저는 작년에 처음 오사카에 갔습니다. 음식이 맛있어서 다시 가고 싶습니다.',question:'화자는 어디에 갔나요?',answer:'오사카에 갔습니다.'},
{id:'l09',level:3,title:'이유 설명',topic:'일상',ko:'비가 와서 집에 있었어요.',ja:'雨が降っていたので、家にいました。',jaKana:'あめが ふっていたので、いえに いました。',en:'I stayed home because it was raining.',literal:'비가 내리고 있었기 때문에 집에 있었습니다.',words:[['비','雨','rain'],['내리다','降る','fall'],['집에 있다','家にいる','stay home']],grammar:'일본어 ので와 영어 because는 이유를 연결합니다. ので는 비교적 부드럽고 객관적인 뉘앙스입니다.',reading:'日曜日は朝から雨でした。外出せず、本を読んで過ごしました。',readingKo:'일요일은 아침부터 비가 왔습니다. 외출하지 않고 책을 읽으며 보냈습니다.',question:'화자는 외출했나요?',answer:'아니요, 외출하지 않았습니다.'},
{id:'l10',level:3,title:'조건 말하기',topic:'계획',ko:'시간이 있으면 같이 점심을 먹어요.',ja:'時間があれば、一緒に昼ご飯を食べましょう。',jaKana:'じかんが あれば、いっしょに ひるごはんを たべましょう。',en:'If you have time, let’s have lunch together.',literal:'시간이 있다면 함께 점심을 먹읍시다.',words:[['시간','時間','time'],['함께','一緒に','together'],['점심','昼ご飯','lunch']],grammar:'일본어 〜ば와 영어 if는 조건을 만듭니다. 〜ましょう와 let’s는 함께 하자는 제안입니다.',reading:'会議が早く終わったら、会社の近くの店へ行く予定です。',readingKo:'회의가 일찍 끝나면 회사 근처 가게에 갈 예정입니다.',question:'어떤 조건에서 가게에 가나요?',answer:'회의가 일찍 끝나면 갑니다.'},
{id:'l11',level:3,title:'의견 말하기',topic:'의견',ko:'제 생각에는 이 방법이 더 효율적이에요.',ja:'私の考えでは、この方法のほうが効率的です。',jaKana:'わたしの かんがえでは、この ほうほうのほうが こうりつてきです。',en:'In my opinion, this method is more efficient.',literal:'내 생각으로는 이 방법 쪽이 효율적입니다.',words:[['생각','考え','opinion'],['방법','方法','method'],['효율적','効率的','efficient']],grammar:'일본어 〜のほうが와 영어 비교급 more는 둘 이상을 비교할 때 사용합니다.',reading:'チームは二つの案を比べました。時間と費用を考えて、二番目の案を選びました。',readingKo:'팀은 두 안을 비교했습니다. 시간과 비용을 고려해 두 번째 안을 선택했습니다.',question:'어떤 안을 선택했나요?',answer:'두 번째 안을 선택했습니다.'},
{id:'l12',level:3,title:'부탁하기',topic:'업무',ko:'이 자료를 오늘 안에 확인해 주실 수 있나요?',ja:'この資料を今日中に確認していただけますか。',jaKana:'この しりょうを きょうじゅうに かくにんして いただけますか。',en:'Could you review this document by the end of today?',literal:'이 자료를 오늘 중으로 확인해 받을 수 있습니까?',words:[['자료','資料','document'],['오늘 안에','今日中に','by today'],['확인하다','確認する','review']],grammar:'일본어 〜ていただけますか와 영어 Could you는 정중한 부탁입니다.',reading:'締め切りは明日の朝です。担当者は今日中の確認をお願いしました。',readingKo:'마감은 내일 아침입니다. 담당자는 오늘 안의 확인을 부탁했습니다.',question:'마감은 언제인가요?',answer:'내일 아침입니다.'},
{id:'l13',level:4,title:'추측 표현',topic:'상황',ko:'아마 길이 많이 막힐 것 같아요.',ja:'たぶん道がかなり混むと思います。',jaKana:'たぶん みちが かなり こむと おもいます。',en:'I think the traffic will probably be heavy.',literal:'아마 도로가 꽤 혼잡할 것이라고 생각합니다.',words:[['아마','たぶん','probably'],['길','道','road'],['막히다','混む','be crowded']],grammar:'일본어 と思います와 영어 I think는 판단을 부드럽게 전달합니다.',reading:'今日は連休の初日なので、高速道路は朝から混雑しています。',readingKo:'오늘은 연휴 첫날이라 고속도로가 아침부터 혼잡합니다.',question:'왜 도로가 혼잡한가요?',answer:'연휴 첫날이기 때문입니다.'},
{id:'l14',level:4,title:'변화 설명',topic:'성장',ko:'꾸준히 연습하면서 발음이 자연스러워졌어요.',ja:'続けて練習するうちに、発音が自然になりました。',jaKana:'つづけて れんしゅうする うちに、はつおんが しぜんに なりました。',en:'My pronunciation became more natural as I kept practicing.',literal:'계속 연습하는 동안 발음이 자연스럽게 되었습니다.',words:[['꾸준히','続けて','consistently'],['발음','発音','pronunciation'],['자연스럽다','自然','natural']],grammar:'일본어 〜うちに는 어떤 과정 중 변화가 생김을 나타냅니다. 영어 as는 동시에 진행되는 변화를 연결합니다.',reading:'毎日十分ずつ音読した結果、以前より速く読めるようになりました。',readingKo:'매일 10분씩 소리 내어 읽은 결과 전보다 빠르게 읽을 수 있게 되었습니다.',question:'무엇을 매일 했나요?',answer:'10분씩 소리 내어 읽었습니다.'},
{id:'l15',level:4,title:'양보 표현',topic:'의견',ko:'어렵기는 하지만 해 볼 가치가 있어요.',ja:'難しいですが、やってみる価値があります。',jaKana:'むずかしいですが、やってみる かちが あります。',en:'Although it is difficult, it is worth trying.',literal:'어렵지만 시도해 볼 가치가 있습니다.',words:[['어렵다','難しい','difficult'],['해 보다','やってみる','try'],['가치','価値','value']],grammar:'일본어 ですが와 영어 although는 반대되는 내용을 연결합니다. worth + 동명사는 “~할 가치가 있다”입니다.',reading:'新しい仕事には覚えることが多いですが、成長できる機会も多いです。',readingKo:'새 일에는 외울 것이 많지만 성장할 기회도 많습니다.',question:'새 일의 장점은 무엇인가요?',answer:'성장할 기회가 많다는 것입니다.'},
{id:'l16',level:4,title:'가정 표현',topic:'상상',ko:'제가 그 상황이었다면 먼저 사과했을 거예요.',ja:'私がその立場だったら、まず謝ったと思います。',jaKana:'わたしが その たちばだったら、まず あやまったと おもいます。',en:'If I had been in that situation, I would have apologized first.',literal:'내가 그 입장이었다면 먼저 사과했을 것이라 생각합니다.',words:[['상황','立場','situation'],['먼저','まず','first'],['사과하다','謝る','apologize']],grammar:'일본어 〜だったら와 영어 과거완료 조건문은 실제와 다른 과거 상황을 가정합니다.',reading:'問題が起きた時、責任者は理由を説明してから皆に謝りました。',readingKo:'문제가 생겼을 때 책임자는 이유를 설명한 뒤 모두에게 사과했습니다.',question:'책임자는 사과 전에 무엇을 했나요?',answer:'이유를 설명했습니다.'},
{id:'l17',level:5,title:'논리적 연결',topic:'업무',ko:'결과가 예상과 달랐으므로 원인을 다시 분석해야 합니다.',ja:'結果が予想と異なったため、原因を改めて分析する必要があります。',jaKana:'けっかが よそうと ことなったため、げんいんを あらためて ぶんせきする ひつようが あります。',en:'Since the result differed from our expectations, we need to analyze the cause again.',literal:'결과가 예상과 달랐기 때문에 원인을 다시 분석할 필요가 있습니다.',words:[['결과','結果','result'],['예상','予想','expectation'],['분석','分析','analysis']],grammar:'일본어 ため와 영어 since는 문어적·논리적인 이유 연결에 자주 쓰입니다.',reading:'テストでは一部の条件だけでエラーが発生しました。チームはログを集め、再現条件を整理しました。',readingKo:'테스트에서는 일부 조건에서만 오류가 발생했습니다. 팀은 로그를 모아 재현 조건을 정리했습니다.',question:'팀은 무엇을 정리했나요?',answer:'재현 조건을 정리했습니다.'},
{id:'l18',level:5,title:'뉘앙스 조절',topic:'대화',ko:'그 의견도 이해하지만 조금 더 검토할 필요가 있다고 봐요.',ja:'その意見も理解できますが、もう少し検討する必要があると思います。',jaKana:'その いけんも りかいできますが、もうすこし けんとうする ひつようが あると おもいます。',en:'I understand that point, but I think we need to consider it a little more.',literal:'그 의견도 이해할 수 있지만 좀 더 검토할 필요가 있다고 생각합니다.',words:[['의견','意見','point'],['이해하다','理解する','understand'],['검토하다','検討する','consider']],grammar:'상대 의견을 먼저 인정한 뒤 but/が로 다른 견해를 연결하면 대화가 부드러워집니다.',reading:'会議では賛成と反対の両方の意見が出ました。結論は次回まで保留になりました。',readingKo:'회의에서는 찬성과 반대 양쪽 의견이 나왔습니다. 결론은 다음 회의까지 보류되었습니다.',question:'결론은 어떻게 되었나요?',answer:'다음 회의까지 보류되었습니다.'}
];

export const NAV=[['today','오늘','☀️'],['course','과정','🧭'],['train','훈련','🎙️'],['review','복습','🧠'],['profile','기록','📊']];
