import{LANGS,LESSONS}from'./data.js';
import{loadState,saveState,resetState,ensureDaily}from'./storage.js';
import{similarity,markMistake,completeSession}from'./learning.js';
import{speak,recognize,Recorder,pronunciationReport}from'./speech.js';
import{$,toast,lessonFor,targetText,layout,todayView,courseView,trainView,reviewView,profileView,lessonCard,modal,enc,escapeHtml}from'./ui.js';
let state=ensureDaily(loadState()),recorder=null,recordResult=null,recognized='';
document.documentElement.dataset.theme=state.theme;
function persist(){saveState(state)}
function render(){ensureDaily(state);const views={today:todayView,course:courseView,train:trainView,review:reviewView,profile:profileView};$('#app').innerHTML=layout(state,views[state.tab](state));document.documentElement.dataset.theme=state.theme;persist()}
function openSession(name){const l=lessonFor(state),src=targetText(l,state.source),target=targetText(l,state.target);if(name==='morning')showModal(`<h2>아침 · 새 문장 배우기</h2>${lessonCard(l,state,false)}<button class="btn primary block" data-finish-session="morning" data-score="100">학습 완료</button>`);if(name==='lunch')showModal(`<h2>점심 · 기억에서 꺼내기</h2><div class="card"><span class="lang-label">${LANGS[state.source].name}</span><div class="sentence">${src}</div></div><textarea id="sessionAnswer" class="text-input" placeholder="${LANGS[state.target].name}로 문장을 입력하세요"></textarea><div id="sessionFeedback"></div><div class="actions"><button class="btn secondary" data-reveal="${enc(target)}">정답 보기</button><button class="btn primary" data-check-recall="lunch">채점하기</button></div>`);if(name==='evening')showModal(`<h2>저녁 · 말하기와 독해</h2><div class="card"><span class="lang-label">발음 목표</span><div class="sentence">${target}</div><div class="actions"><button class="btn secondary" data-speak="${state.target}" data-text="${enc(target)}">🔊 듣기</button><button class="btn primary" data-open-pronunciation="1">🎙️ 말하기</button></div></div><div class="card"><span class="lang-label">짧은 독해</span><p class="sentence" style="font-size:19px">${l.reading}</p><p class="reading">${l.readingKo}</p><p><b>${l.question}</b></p><textarea id="readingAnswer" class="text-input" placeholder="한국어로 답해 보세요"></textarea><div id="readingFeedback"></div><button class="btn primary block" data-check-reading="1">독해 확인</button></div>`)}
function showModal(html){$('#modalRoot').innerHTML=modal(html)}
function closeModal(){const root=$('#modalRoot');if(root)root.innerHTML=''}
function openTrain(type){const l=lessonFor(state),target=targetText(l,state.target),src=targetText(l,state.source);if(type==='pronunciation')return openPronunciation();if(type==='dictation')showModal(`<h2>받아쓰기</h2><div class="card"><p>모델 음성을 듣고 그대로 입력하세요.</p><button class="btn primary block" data-speak="${state.target}" data-text="${enc(target)}">🔊 문장 듣기</button></div><textarea id="trainAnswer" class="text-input" placeholder="들은 문장을 입력하세요"></textarea><div id="trainFeedback"></div><button class="btn primary block" data-check-train="dictation">채점하기</button>`);if(type==='recall')showModal(`<h2>문장 회상</h2><div class="card"><span class="lang-label">${LANGS[state.source].name}</span><div class="sentence">${src}</div></div><textarea id="trainAnswer" class="text-input" placeholder="${LANGS[state.target].name}로 바꿔 보세요"></textarea><div id="trainFeedback"></div><button class="btn primary block" data-check-train="recall">채점하기</button>`);if(type==='reading')showModal(`<h2>독해 훈련</h2><div class="card"><p class="sentence" style="font-size:19px">${l.reading}</p><p class="reading">${l.readingKo}</p><p><b>${l.question}</b></p></div><textarea id="trainAnswer" class="text-input" placeholder="답을 입력하세요"></textarea><div id="trainFeedback"></div><button class="btn primary block" data-check-train="reading">확인하기</button>`)}
function openPronunciation(){const l=lessonFor(state),target=targetText(l,state.target);recordResult=null;recognized='';showModal(`<h2>발음 코칭</h2><div class="notice">웹판은 문장 인식 정확도·속도·침묵·피치 변화량을 기초 분석합니다. 실제 음소/피치 악센트 정밀 판정은 최종 앱 단계에서 강화합니다.</div><div class="card"><span class="lang-label">${LANGS[state.target].name}</span><div class="sentence">${target}</div>${state.target==='ja'?`<div class="reading">${l.jaKana}</div>`:''}<div class="actions"><button class="btn secondary" data-speak="${state.target}" data-text="${enc(target)}">🔊 모델</button><button class="btn secondary" data-speak-slow="${state.target}" data-text="${enc(target)}">🐢 느리게</button></div></div><div id="recordArea"><button class="btn primary block" data-record-start="1">● 녹음 시작</button></div><div id="recognitionArea"><button class="btn secondary block" data-recognize="1">🎤 음성 인식 시작</button></div><textarea id="manualTranscript" class="text-input" placeholder="음성 인식이 안 되면 말한 문장을 직접 입력하세요"></textarea><button class="btn good block" data-analyze-pronunciation="1">발음 결과 분석</button><div id="pronunciationResult"></div>`)}
async function startRecording(){try{recorder=new Recorder();await recorder.start();$('#recordArea').innerHTML=`<div class="recording"><span class="pulse"></span> 녹음 중…</div><button class="btn bad block" data-record-stop="1">■ 녹음 종료</button>`}catch(e){toast('마이크 권한을 허용해 주세요.') }}
async function stopRecording(){recordResult=await recorder.stop();$('#recordArea').innerHTML=`<audio controls src="${recordResult.url}" style="width:100%"></audio><p class="muted">${recordResult.duration.toFixed(1)}초 녹음 · 침묵 ${Math.round(recordResult.silenceRatio*100)}%</p><button class="btn primary block" data-record-start="1">다시 녹음</button>`}
function startRecognition(){const area=$('#recognitionArea');recognize(state.target,{onStart:()=>area.innerHTML='<div class="recording"><span class="pulse"></span> 듣고 있어요…</div>',onResult:r=>{const text=r.final||r.interim;$('#manualTranscript').value=text;if(r.final)recognized=r.final},onError:e=>{area.innerHTML=`<div class="answer-box bad">${escapeHtml(e.message)}</div>`},onEnd:()=>{area.innerHTML='<button class="btn secondary block" data-recognize="1">🎤 다시 인식</button>'}})}
function analyzePronunciation(){const l=lessonFor(state),target=targetText(l,state.target),transcript=$('#manualTranscript').value.trim()||recognized;if(!transcript)return toast('인식된 문장이나 직접 입력한 문장이 필요합니다.');const report=pronunciationReport({transcript,target,lang:state.target,duration:recordResult?.duration||0,silenceRatio:recordResult?.silenceRatio||0,pitchVariation:recordResult?.pitchVariation||0});state.pronunciationHistory.push({lessonId:l.id,title:l.title,lang:state.target,total:report.total,at:Date.now()});state.xp+=report.total>=80?15:8;if(report.accuracy<80)markMistake(state,l.id,'발음',transcript,target);persist();$('#pronunciationResult').innerHTML=`<div class="card"><div class="score-row"><div class="score-ring" style="--score:${report.total}"><b>${report.total}</b></div><div class="score-copy"><h3>기초 발음 분석</h3><p class="muted">${report.note}</p></div></div><div class="breakdown"><div><b>${report.accuracy}</b><small>문장 정확도</small></div><div><b>${report.paceScore}</b><small>속도 균형</small></div><div><b>${report.silenceScore}</b><small>끊김</small></div><div><b>${report.intonationScore}</b><small>피치 변화</small></div></div><h3>문장 비교</h3><div class="diff">${report.diff.map(x=>`<span class="${x.type}">${escapeHtml(x.value)}${state.target==='en'?' ':''}</span>`).join('')}</div></div>`}
function checkRecall(session='lunch'){const l=lessonFor(state),answer=$('#sessionAnswer').value,target=targetText(l,state.target),score=similarity(answer,target,state.target);if(score<80)markMistake(state,l.id,'문장 회상',answer,target);completeSession(state,session,score);persist();$('#sessionFeedback').innerHTML=`<div class="answer-box ${score>=80?'good':'bad'}"><b>${score}점</b><br>${score>=80?'정확하게 기억했습니다.':'정답: '+escapeHtml(target)}</div>`;renderAfterModal()}
function checkReading(fromEvening=false){const l=lessonFor(state),el=$(fromEvening?'#readingAnswer':'#trainAnswer'),answer=el.value.trim();const ok=l.answer.replace(/\s/g,'').includes(answer.replace(/\s/g,''))||answer.replace(/\s/g,'').includes(l.answer.replace(/\s/g,''));if(!ok)markMistake(state,l.id,'독해',answer,l.answer);if(fromEvening)completeSession(state,'evening',ok?100:40);else state.xp+=ok?10:3;persist();$(fromEvening?'#readingFeedback':'#trainFeedback').innerHTML=`<div class="answer-box ${ok?'good':'bad'}">${ok?'핵심을 정확히 찾았습니다.':'정답: '+escapeHtml(l.answer)}</div>`;renderAfterModal()}
function checkTrain(type){const l=lessonFor(state),answer=$('#trainAnswer').value.trim();if(type==='reading')return checkReading(false);const target=targetText(l,state.target),score=similarity(answer,target,state.target);if(score<80)markMistake(state,l.id,type==='dictation'?'받아쓰기':'문장 회상',answer,target);state.xp+=score>=80?10:3;persist();$('#trainFeedback').innerHTML=`<div class="answer-box ${score>=80?'good':'bad'}"><b>${score}점</b><br>${score>=80?'정답입니다.':'정답: '+escapeHtml(target)}</div>`;renderAfterModal()}
function renderAfterModal(){const html=$('#modalRoot').innerHTML;render();$('#modalRoot').innerHTML=html}
function selectLesson(id){const found=LESSONS.find(x=>x.id===id),list=LESSONS.filter(l=>l.level<=Math.max(state.level,found.level));state.level=Math.max(state.level,found.level);state.lessonIndex=list.findIndex(l=>l.id===id);state.tab='today';render();scrollTo(0,0)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){state.tab=b.dataset.tab;render();scrollTo(0,0);return}if(b.dataset.action==='theme'){state.theme=state.theme==='dark'?'light':'dark';render();return}if(b.dataset.action==='swap'){[state.source,state.target]=[state.target,state.source];if(state.source===state.target)state.target=state.target==='ja'?'en':'ja';render();return}if(b.dataset.action==='reset'){if(confirm('학습 기록을 모두 초기화할까요?')){state=ensureDaily(resetState());render()}return}if(b.dataset.action==='close-modal')closeModal();if(b.dataset.session)openSession(b.dataset.session);if(b.dataset.lesson)selectLesson(b.dataset.lesson);if(b.dataset.train)openTrain(b.dataset.train);if(b.dataset.speak)speak(decodeURIComponent(b.dataset.text),b.dataset.speak,state.settings.normalRate);if(b.dataset.speakSlow)speak(decodeURIComponent(b.dataset.text),b.dataset.speakSlow,state.settings.slowRate);if(b.dataset.finishSession){completeSession(state,b.dataset.finishSession,+b.dataset.score);closeModal();render();toast('오늘 학습에 기록했습니다.')}if(b.dataset.reveal)toast(decodeURIComponent(b.dataset.reveal));if(b.dataset.checkRecall)checkRecall(b.dataset.checkRecall);if(b.dataset.openPronunciation)openPronunciation();if(b.dataset.recordStart)startRecording();if(b.dataset.recordStop)stopRecording();if(b.dataset.recognize)startRecognition();if(b.dataset.analyzePronunciation)analyzePronunciation();if(b.dataset.checkReading)checkReading(true);if(b.dataset.checkTrain)checkTrain(b.dataset.checkTrain);if(b.dataset.reviewDone){state.mistakes.splice(+b.dataset.reviewDone,1);render();toast('오답을 해결 처리했습니다.')}if(b.dataset.reviewSpeak){const item=state.mistakes[+b.dataset.reviewSpeak];if(item)speak(item.answer,state.target,.85)}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.field){state[el.dataset.field]=el.value;if(state.source===state.target)state.target=state.target==='ja'?'en':'ja';render()}if(el.dataset.setting==='showAllLanguages'){state.settings.showAllLanguages=el.checked;render()}if(el.dataset.setting==='level'){state.level=+el.value;state.lessonIndex=0;render()}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
