import{LANGS}from'./data.js';
import{similarity,diffTokens}from'./learning.js';
export function speak(text,lang,rate=1){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=LANGS[lang].speech;u.rate=rate;const voices=speechSynthesis.getVoices();const exact=voices.find(v=>v.lang.toLowerCase()===u.lang.toLowerCase())||voices.find(v=>v.lang.toLowerCase().startsWith(lang));if(exact)u.voice=exact;speechSynthesis.speak(u)}
export function recognize(lang,{onStart,onResult,onError,onEnd}={}){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){onError?.(new Error('이 브라우저는 음성 인식을 지원하지 않습니다.'));return null}const r=new R();r.lang=LANGS[lang].speech;r.interimResults=true;r.continuous=false;r.onstart=()=>onStart?.();r.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?final+=t:interim+=t}onResult?.({final,interim})};r.onerror=e=>onError?.(new Error(e.error||'음성 인식 오류'));r.onend=()=>onEnd?.();r.start();return r}
export class Recorder{
  constructor(){this.stream=null;this.recorder=null;this.chunks=[];this.started=0;this.silenceSamples=0;this.totalSamples=0;this.pitchValues=[];this.timer=null;this.audioContext=null;this.analyser=null}
  async start(){this.stream=await navigator.mediaDevices.getUserMedia({audio:true});this.recorder=new MediaRecorder(this.stream);this.chunks=[];this.recorder.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data)};this.recorder.start(250);this.started=performance.now();this.audioContext=new AudioContext();const source=this.audioContext.createMediaStreamSource(this.stream);this.analyser=this.audioContext.createAnalyser();this.analyser.fftSize=2048;source.connect(this.analyser);const data=new Float32Array(this.analyser.fftSize);this.timer=setInterval(()=>{this.analyser.getFloatTimeDomainData(data);let sum=0;for(const x of data)sum+=x*x;const rms=Math.sqrt(sum/data.length);this.totalSamples++;if(rms<.015)this.silenceSamples++;const pitch=estimatePitch(data,this.audioContext.sampleRate);if(pitch>60&&pitch<450)this.pitchValues.push(pitch)},120)}
  async stop(){if(!this.recorder)return null;return new Promise(resolve=>{this.recorder.onstop=()=>{clearInterval(this.timer);const duration=(performance.now()-this.started)/1000;const blob=new Blob(this.chunks,{type:this.recorder.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);const silenceRatio=this.totalSamples?this.silenceSamples/this.totalSamples:0;const pitchVariation=variation(this.pitchValues);this.stream.getTracks().forEach(t=>t.stop());this.audioContext?.close();resolve({blob,url,duration,silenceRatio,pitchVariation})};this.recorder.stop()})}
}
function variation(values){if(values.length<3)return 0;const mean=values.reduce((a,b)=>a+b,0)/values.length;const variance=values.reduce((s,x)=>s+(x-mean)**2,0)/values.length;return Math.min(100,Math.round(Math.sqrt(variance)/mean*240))}
function estimatePitch(buffer,sampleRate){let size=buffer.length,rms=0;for(let i=0;i<size;i++)rms+=buffer[i]*buffer[i];rms=Math.sqrt(rms/size);if(rms<.01)return-1;let bestOffset=-1,best=0;for(let offset=20;offset<Math.min(1000,size/2);offset++){let corr=0;for(let i=0;i<size-offset;i++)corr+=buffer[i]*buffer[i+offset];if(corr>best){best=corr;bestOffset=offset}}return bestOffset>0?sampleRate/bestOffset:-1}
export function pronunciationReport({transcript,target,lang,duration=0,silenceRatio=0,pitchVariation=0}){const accuracy=similarity(transcript,target,lang);const units=Math.max(1,lang==='en'?target.trim().split(/\s+/).length:[...target.replace(/\s/g,'')].length);const perMin=duration?Math.round(units/duration*60):0;const paceTarget=lang==='en'?125:lang==='ja'?260:230;const paceScore=duration?Math.max(20,100-Math.round(Math.abs(perMin-paceTarget)/paceTarget*100)):0;const silenceScore=Math.max(0,Math.round(100-silenceRatio*150));const intonationScore=Math.min(100,Math.max(35,pitchVariation*1.25));const total=Math.round(accuracy*.58+paceScore*.16+silenceScore*.14+intonationScore*.12);return{accuracy,paceScore,silenceScore,intonationScore,total,perMin,diff:diffTokens(transcript,target,lang),note:coachNote(lang,{accuracy,paceScore,silenceRatio,pitchVariation})}}
function coachNote(lang,m){if(m.accuracy<60)return lang==='ja'?'장음·촉음·조사를 한 덩어리씩 끊어 다시 말해 보세요.':lang==='en'?'단어 끝소리와 핵심 강세를 천천히 확인하세요.':'받침과 연음 구간을 한 음절씩 확인하세요.';if(m.silenceRatio>.3)return'문장을 짧은 의미 단위로 나누되 중간 침묵은 줄여 보세요.';if(m.paceScore<65)return'모델 음성을 느리게 듣고 같은 리듬으로 한 번 더 따라 말해 보세요.';if(m.pitchVariation<15)return'문장 끝과 핵심 단어에 억양 변화를 조금 더 주세요.';return'정확도가 좋습니다. 이제 자연스러운 속도로 한 번 더 말해 보세요.'}
