import{LANGS,LESSONS,NAV}from'./data.js';
import{dueReviews}from'./learning.js';
export const $=s=>document.querySelector(s);
export function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
export function lessonFor(state){const eligible=LESSONS.filter(l=>l.level<=state.level);return eligible[state.lessonIndex%eligible.length]||LESSONS[0]}
export function targetText(lesson,lang){return lesson[lang]}
export function layout(state,content){return`<main class="app-shell"><header class="topbar"><div class="brand"><div class="logo">하루</div><div><h1>하루언어</h1><p>한국어 · 日本語 · English</p></div></div><button class="icon-btn" data-action="theme">${state.theme==='dark'?'☀️':'🌙'}</button></header>${content}</main><nav class="bottom-nav">${NAV.map(([id,name,icon])=>`<button class="nav-btn ${state.tab===id?'active':''}" data-tab="${id}"><i>${icon}</i>${name}</button>`).join('')}</nav><div id="modalRoot"></div>`}
export function pairSelector(state){return`<div class="card"><div class="pair-select"><select class="select" data-field="source">${langOptions(state.source)}</select><button class="swap" data-action="swap">⇄</button><select class="select" data-field="target">${langOptions(state.target)}</select></div></div>`}
function langOptions(value){return Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${value===k?'selected':''}>${v.name}</option>`).join('')}
export function todayView(state){const l=lessonFor(state),done=[state.daily.morning,state.daily.lunch,state.daily.evening].filter(Boolean).length;return`${pairSelector(state)}<section class="card hero"><h2>${greeting()} 👋</h2><p>오늘은 “${l.title}” 문장을 세 번에 나눠 완전히 익혀요.</p><div class="hero-row"><div class="xp-pill">🔥 ${state.streak}일 연속</div><b>${done}/3 완료</b></div></section><div class="grid three"><div class="metric"><b>${state.xp}</b><span>누적 XP</span></div><div class="metric"><b>${dueReviews(state,LESSONS).length}</b><span>복습 예정</span></div><div class="metric"><b>L${state.level}</b><span>현재 단계</span></div></div><div class="section-title"><h2>오늘의 집중 학습</h2><span>${Math.round(done/3*100)}%</span></div><div class="progress"><i style="width:${done/3*100}%"></i></div><div class="card session-list">${sessionItem('morning','🌅','아침 · 새 문장 배우기','뜻·단어·문법과 모델 음성',state.daily.morning)}${sessionItem('lunch','☀️','점심 · 기억에서 꺼내기','번역 없이 직접 문장 만들기',state.daily.lunch)}${sessionItem('evening','🌙','저녁 · 말하기와 독해','발음 분석·짧은 지문 확인',state.daily.evening)}</div><div class="section-title"><h2>오늘의 문장</h2><span>${l.topic}</span></div>${lessonCard(l,state,true)}`}
function sessionItem(id,icon,title,sub,done){return`<button class="session-item" data-session="${id}"><span class="session-icon">${done?'✅':icon}</span><span class="session-copy"><b>${title}</b><small>${sub}</small></span><span>›</span></button>`}
export function lessonCard(l,state,compact=false){const lines=state.settings.showAllLanguages?['ko','ja','en']:[state.target];return`<article class="card">${lines.map(k=>`<div class="lang-line"><span class="lang-label">${LANGS[k].name}</span><div class="sentence">${l[k]}</div>${k==='ja'?`<div class="reading">${l.jaKana}</div>`:''}<div class="actions"><button class="btn secondary" data-speak="${k}" data-text="${enc(l[k])}">🔊 듣기</button><button class="btn secondary" data-speak-slow="${k}" data-text="${enc(l[k])}">🐢 느리게</button></div></div>`).join('')}${compact?'':`<h3>핵심 단어</h3><div class="word-grid">${l.words.map(w=>`<div class="word"><b>${w[0]} · ${w[1]}</b><small>${w[2]}</small></div>`).join('')}</div><h3>문법 코치</h3><p class="muted">${l.grammar}</p>`}</article>`}
export function courseView(state){const levels=[1,2,3,4,5];return`${pairSelector(state)}<section class="card hero"><h2>기초부터 실전까지</h2><p>회화·단어·문법·독해·발음을 같은 문장 안에서 연결합니다.</p></section>${levels.map(level=>{const list=LESSONS.filter(l=>l.level===level);return`<div class="section-title"><h2>Level ${level}</h2><span>${list.length}개 수업</span></div><div class="card">${list.map(l=>`<button class="session-item" data-lesson="${l.id}"><span class="course-level">L${level}</span><span class="course-body"><b>${l.title}</b><small>${l.topic} · ${l[state.target]}</small></span><span>›</span></button>`).join('')}</div>`}).join('')}`}
export function trainView(state){const l=lessonFor(state);return`${pairSelector(state)}<section class="card hero"><h2>집중 훈련</h2><p>정답을 보기 전에 직접 듣고, 쓰고, 말해 보세요.</p></section><div class="grid"><button class="metric" data-train="pronunciation"><b>🎙️</b><span>발음 코칭</span></button><button class="metric" data-train="dictation"><b>🎧</b><span>받아쓰기</span></button><button class="metric" data-train="reading"><b>📖</b><span>독해</span></button><button class="metric" data-train="recall"><b>🧩</b><span>문장 회상</span></button></div><div class="section-title"><h2>추천 훈련 문장</h2><span>${l.title}</span></div>${lessonCard(l,state,true)}`}
export function reviewView(state){const due=dueReviews(state,LESSONS);return`<section class="card hero"><h2>오답 복습</h2><p>틀린 횟수가 많은 문장부터 다시 익힙니다.</p></section>${due.length?due.map(x=>`<article class="card"><span class="lang-label">${x.type} · ${x.count}회</span><h3>${x.lesson.title}</h3><p class="muted">내 답: ${escapeHtml(x.input||'')}</p><p><b>정답:</b> ${escapeHtml(x.answer)}</p><div class="actions"><button class="btn secondary" data-review-speak="${x.index}">정답 듣기</button><button class="btn good" data-review-done="${x.index}">해결 완료</button></div></article>`).join(''):`<div class="card empty"><div style="font-size:42px">🎉</div><h3>복습할 오답이 없어요</h3><p>오늘 학습을 진행하면 취약 문장이 여기에 모입니다.</p></div>`}`}
export function profileView(state){const avg=state.pronunciationHistory.length?Math.round(state.pronunciationHistory.reduce((s,x)=>s+x.total,0)/state.pronunciationHistory.length):0;return`<section class="card hero"><h2>학습 기록</h2><p>점수보다 반복해서 좋아지는 흐름을 확인하세요.</p></section><div class="grid three"><div class="metric"><b>${state.xp}</b><span>XP</span></div><div class="metric"><b>${state.streak}</b><span>연속일</span></div><div class="metric"><b>${avg||'-'}</b><span>평균 발음</span></div></div><div class="card"><div class="setting"><div><b>표시 언어</b><small>세 언어 문장을 함께 표시</small></div><input type="checkbox" data-setting="showAllLanguages" ${state.settings.showAllLanguages?'checked':''}></div><div class="setting"><div><b>현재 레벨</b><small>학습 문장 난이도</small></div><select class="select" style="width:110px" data-setting="level">${[1,2,3,4,5].map(x=>`<option ${state.level===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="setting"><div><b>데이터 초기화</b><small>기기 안의 학습 기록 삭제</small></div><button class="btn bad" data-action="reset">초기화</button></div></div><div class="section-title"><h2>최근 발음 기록</h2><span>${state.pronunciationHistory.length}회</span></div>${state.pronunciationHistory.length?`<div class="card">${state.pronunciationHistory.slice(-6).reverse().map(x=>`<div class="setting"><div><b>${x.title}</b><small>${new Date(x.at).toLocaleDateString()} · ${LANGS[x.lang].name}</small></div><strong>${x.total}점</strong></div>`).join('')}</div>`:`<div class="card empty">아직 발음 기록이 없습니다.</div>`}`}
function greeting(){const h=new Date().getHours();return h<11?'좋은 아침이에요':h<17?'오늘도 잘하고 있어요':'저녁 복습을 시작해요'}
export function modal(content){return`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><div class="modal-handle"></div><div style="display:flex;justify-content:flex-end;margin-bottom:6px"><button class="icon-btn" data-action="close-modal" aria-label="닫기">✕</button></div>${content}</section></div>`}
export function enc(v){return encodeURIComponent(v)}
export function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
